// Every user-facing string lives here so the UI can be translated later.
// Functions are used where a string needs values interpolated.

export const strings = {
  appName: "Lodestar",
  tagline: "Local code-base assistant",

  common: {
    cancel: "Cancel",
    save: "Save",
    skipToContent: "Skip to content",
    moreActions: (title: string) => `${title}: more actions`,
    copyCode: "Copy code",
    copied: "Copied",
    source: (n: number) => `Source ${n}`,
    openSource: (n: number, path?: string) => `Open source ${n}${path ? `: ${path}` : ""}`,
    repoCount: (n: number) => `${n} ${n === 1 ? "repository" : "repositories"}`,
    chunksAgo: (chunks: number, when: string) => `${chunks.toLocaleString()} chunks · ${when}`,
    reindexed: (name: string, changed: number, removed: number) =>
      `${name} re-indexed · ${changed} changed, ${removed} removed`,
    notDownloadedSuffix: " · not downloaded",
  },

  sidebar: {
    repositories: "Repository",
    addRepository: "Add repository",
    conversations: "Conversations",
    newChat: "New chat",
    noConversations: "No conversations yet.",
    settings: "Settings",
    collapse: "Collapse sidebar",
    expand: "Expand sidebar",
    rename: "Rename",
    delete: "Delete",
    deleteConfirm: "Delete this conversation?",
    removeRepo: "Remove repository",
    removeRepoConfirm: (name: string) =>
      `Remove "${name}" and delete its index? Your files are not touched.`,
    switchRepo: "Switch repository",
    workspace: "Workspace",
    chat: "Chat",
    runtime: "Runtime",
    running: "Foundry Local running",
    onGpu: "GPU acceleration on",
    onCpu: "Running on CPU",
    stopped: "Foundry Local offline",
    starting: "Starting Foundry Local…",
  },

  theme: {
    label: "Theme",
    toggle: "Toggle theme",
    light: "Light",
    dark: "Dark",
    system: "System",
  },

  topbar: {
    chat: "Chat",
    settings: "Settings",
    reindex: "Re-index",
    indexing: "Indexing…",
    notIndexed: "Not indexed",
    indexed: (chunks: number, when: string) =>
      `Indexed · ${chunks.toLocaleString()} chunks · ${when}`,
  },

  onboarding: {
    eyebrow: "100% local · Powered by Foundry Local",
    title: "Ask questions about your code",
    subtitle:
      "Lodestar indexes a local repository and answers questions with citations. Everything runs on this machine.",
    pathLabel: "Repository folder",
    pathPlaceholder: "C:\\Users\\you\\projects\\my-app  or  /home/you/my-app",
    add: "Add repository",
    adding: "Adding…",
    steps: [
      { title: "Add a repository", body: "Point Lodestar at a folder on this computer." },
      { title: "Index it", body: "Code is split into functions and classes, then embedded." },
      { title: "Ask", body: "Get grounded answers with file and line references." },
    ],
    status: "Local runtime",
    foundry: "Foundry Local",
    chatModel: "Chat model",
    embeddings: "Embeddings",
    ready: "Ready",
    notReady: "Not ready",
    starting: "Starting…",
    previous: "Previously indexed",
    tryExample: "Tip: try the sample repo in examples/bookshelf.",
    features: [
      { title: "Code-aware", body: "Chunks follow functions, methods and classes." },
      { title: "Hybrid search", body: "Semantic vectors plus BM25 keyword matching." },
      { title: "Private by design", body: "No cloud APIs, no telemetry, no CDNs." },
    ],
  },

  indexing: {
    title: "Indexing repository",
    scanning: "Scanning files",
    embedding: "Embedding chunks",
    analyzing: "Analyzing code structure",
    done: "Indexing complete",
    failed: "Indexing failed",
    files: "Files scanned",
    changed: "Changed",
    chunks: "Chunks created",
    embedded: "Chunks embedded",
    elapsed: "Elapsed",
    recent: "Recent files",
    startChatting: "Start asking questions",
  },

  chat: {
    emptyTitle: (repo: string) => `Ask anything about ${repo}`,
    emptySubtitle: "Answers are grounded in the indexed code and cite their sources.",
    suggestions: [
      { title: "Authentication", question: "How does authentication work in this project?" },
      { title: "Data model", question: "Where is the database schema defined?" },
      { title: "Architecture", question: "What are the main entry points of the application?" },
    ],
    placeholder: "Ask a question about the code…",
    send: "Send",
    stop: "Stop",
    hint: "Answers are generated locally",
    shortcuts: "Enter to send · Shift+Enter for a new line · Ctrl+K to focus",
    sendHint: "send",
    newLineHint: "new line",
    focusHint: "focus",
    you: "You",
    assistant: "Lodestar",
    thinking: "Searching the code…",
    generating: "Generating answer… (the first answer after a restart can take a minute)",
    copy: "Copy answer",
    copied: "Copied",
    regenerate: "Regenerate",
    sources: (n: number) => `Sources (${n})`,
    retrieved: (n: number) => `Retrieved context (${n})`,
    rewritten: (q: string) => `Searched for: “${q}”`,
    errorTitle: "Could not answer",
    retry: "Try again",
  },

  noAnswer: {
    title: "Nothing relevant found",
    body: "I couldn't find anything relevant to this question in the indexed code. Try naming a file, function or feature, or lower the relevance threshold in Settings.",
    closest: "Closest matches",
    score: (s: number) => `similarity ${s.toFixed(2)}`,
  },

  source: {
    title: "Source",
    lines: (a: number, b: number) => `Lines ${a}–${b}`,
    score: "Score",
    similarity: "Similarity",
    stale: "The file changed since it was indexed. Showing the indexed version.",
    close: "Close",
    copyPath: "Copy path",
    loading: "Loading source…",
  },

  settings: {
    title: "Settings",
    subtitle: "Configure the local model, retrieval and appearance.",
    appearance: "Appearance",
    appearanceHelp: "Choose a light or dark interface, or follow your system setting.",
    back: "Back to chat",
    model: "Model",
    modelHelp: "Chat models run on this device through Foundry Local.",
    chatModel: "Chat model",
    download: "Download",
    load: "Load",
    loaded: "Loaded",
    device: (d: string) => `Runs on ${d}`,
    cached: "Downloaded",
    notDownloaded: "Not downloaded",
    downloading: (pct: number) => `Downloading ${Math.round(pct)}%`,
    loading: "Loading…",
    embeddingModel: "Embedding model",
    embeddingHelp: "Set with LODESTAR_EMBEDDING_MODEL. Changing it re-indexes repositories.",
    retrieval: "Retrieval",
    retrievalHelp: "How many snippets are sent to the model and when Lodestar refuses to answer.",
    topK: "Snippets per answer (top-K)",
    threshold: "Relevance threshold",
    thresholdHelp:
      "If the best match is less similar than this, Lodestar says it does not know instead of asking the model.",
    hybrid: "Hybrid search",
    hybridHelp: "Combine semantic search with keyword (BM25) search.",
    privacy: "About & privacy",
    localOnly: "Local only",
    localOnlyOn: "No external network connections",
    localOnlyOff: "External connection attempts detected",
    privacyBody:
      "Your code, questions and embeddings never leave this machine. The backend blocks every outbound connection that is not to localhost, and the UI loads no fonts, icons or scripts from the internet.",
    endpoint: "Foundry Local endpoint",
    blocked: "Blocked connection attempts",
    version: "Version",
    saved: "Settings saved",
    foundryDown: "Foundry Local is not running",
  },

  insights: {
    title: "Insights",
    nav: {
      overview: "Overview",
      impact: "Impact analysis",
      diagrams: "Diagrams",
      endpoints: "API endpoints",
      config: "Config & env",
      docs: "Docstrings",
      duplicates: "Duplicates",
      debt: "Tech debt",
    },
    lastAnalyzed: (when: string) => `Last analyzed ${when}`,
    neverAnalyzed: "Not analyzed yet",
    reanalyze: "Re-analyze",
    analyzeNow: "Analyze now",
    analyzing: "Analyzing…",
    progress: (done: number, total: number) => `${done} of ${total} files`,
    notAnalyzedTitle: "This repository has not been analyzed yet",
    notAnalyzedBody:
      "Insights are computed from your code on this machine. Run the analysis once to fill this page.",
    notIndexedBody: "Index the repository first, then come back to run the analysis.",
    heuristic:
      "Heuristic analysis: anything matched by name can be wrong, so results show how sure we are.",
    failed: "The analysis failed.",
    done: "Analysis complete",
    open: "Open",
    overview: {
      subtitle: "What Lodestar found in this repository.",
      symbols: "Symbols",
      symbolsHelp: "Functions, methods and classes",
      endpoints: "API endpoints",
      env: "Environment variables",
      undocumented: "Undocumented functions",
      duplicates: "Duplicate groups",
      debt: "Tech debt items",
      soon: "Coming soon",
    },
    config: {
      title: "Config and environment variables",
      subtitle: "Every variable the code reads, and a ready-made .env.example.",
      tabVariables: "Variables",
      tabExample: ".env.example",
      search: "Search variables",
      name: "Name",
      required: "Required",
      optional: "Optional",
      secret: "Secret",
      secretHint: "Looks like a secret: its default value is never stored or written to a file.",
      default: "Default",
      hidden: "hidden",
      varies: "varies",
      none: "none",
      usages: "Used in",
      declared: "Declared",
      declaredIn: (files: string) => `Declared in ${files}`,
      notDeclared: "Not declared in any .env file",
      emptyTitle: "No environment variables found",
      emptyBody: "Nothing in this repository reads an environment variable.",
      copy: "Copy",
      download: "Download",
      copied: "Copied .env.example",
      exampleHelp: "Secrets are left empty. Review it before you commit the file.",
      privacy: "Lodestar never reads the values in your .env files, only the names.",
      variables: (n: number) => `${n} ${n === 1 ? "variable" : "variables"}`,
      places: (n: number) => `${n} ${n === 1 ? "place" : "places"}`,
    },
    docs: {
      title: "Docstring suggestions",
      subtitle:
        "Draft doc comments for undocumented functions. You review each one before anything is written.",
      banner: "This feature edits files in your repository. A backup is created first.",
      bannerDetail:
        "Backups go to .lodestar-backup/ in the repository. Nothing is written until you accept.",
      tabs: { missing: "Undocumented", review: "Review" },
      search: "Search functions or files",
      language: "Language",
      allLanguages: "All languages",
      minLines: "Smallest function",
      includeTests: "Include tests",
      count: (n: number) => `${n} undocumented`,
      selectAll: "Select all shown",
      selectNone: "Clear selection",
      selected: (n: number) => `${n} selected`,
      generate: (n: number) => `Generate for ${n}`,
      generating: (done: number, total: number) => `Generating ${done} of ${total}`,
      generatingNow: (name: string) => `Working on ${name}`,
      jobFailed: (n: number) => `${n} could not be generated`,
      jobDone: "Suggestions are ready to review.",
      goReview: "Review",
      callers: (n: number) => `${n} ${n === 1 ? "caller" : "callers"}`,
      lines: (n: number) => `${n} lines`,
      suggested: "Suggested",
      failed: "Failed",
      emptyTitle: "Everything here is documented",
      emptyBody: "No undocumented functions match these filters.",
      reviewEmptyTitle: "Nothing to review",
      reviewEmptyBody: "Choose functions on the Undocumented tab and generate suggestions.",
      status: { pending: "Pending", accepted: "Applied", rejected: "Rejected", failed: "Failed" },
      filterStatus: "Show",
      showDiff: "Show change",
      hideDiff: "Hide change",
      accept: "Accept",
      reject: "Reject",
      regenerate: "Regenerate",
      acceptAll: (n: number) => `Accept all valid (${n})`,
      confirmTitle: "Write docstrings to your repository?",
      confirmBody: (n: number, files: number) =>
        `${n} ${n === 1 ? "docstring" : "docstrings"} will be added to ${files} ${files === 1 ? "file" : "files"}. Each file is backed up first, and only comment text is inserted.`,
      confirm: "Write to files",
      cancel: "Cancel",
      applied: (n: number, files: number) =>
        `Added ${n} ${n === 1 ? "docstring" : "docstrings"} to ${files} ${files === 1 ? "file" : "files"}.`,
      appliedSome: (ok: number, bad: number) => `${ok} applied, ${bad} refused.`,
      rejectedToast: "Suggestion rejected.",
      reindexSkipped: "Indexing was busy. Re-analyze the repository to refresh the list.",
      loadingDiff: "Preparing the change",
      styleNote: (style: string) => `Python style: ${style}`,
    },
    duplicates: {
      title: "Duplicate code",
      subtitle: "Groups of functions that repeat each other: candidates to refactor together.",
      similarity: "Minimum similarity",
      type: "Match type",
      types: { all: "All", exact: "Exact", similar: "Similar" },
      typeBadge: { exact: "Exact clone", similar: "Similar" },
      typeHint: {
        exact: "The same code once names and values are ignored.",
        similar: "Close in meaning, but not the same structure.",
      },
      includeTests: "Include tests",
      minLines: "Smallest function",
      lines: (n: number) => `${n} lines`,
      groups: (n: number) => `${n} ${n === 1 ? "group" : "groups"}`,
      duplicatedLines: (n: number) => `${n.toLocaleString()} duplicated lines`,
      members: (n: number) => `${n} functions`,
      more: (n: number) => `+${n} more`,
      value: "Refactor value",
      valueHint: "Group size times duplicated lines: bigger means more to gain.",
      compare: "Compare",
      compareA: "First function",
      compareB: "Second function",
      pickTwo: "Choose two different functions to compare.",
      identical: "These two are identical after names are ignored.",
      changed: (pct: number) => `${pct}% of the lines match`,
      left: "Left",
      right: "Right",
      export: "Markdown",
      emptyTitle: "No duplicates found",
      emptyBody: "Nothing at this similarity. Lower the threshold to see closer calls.",
      floor: (n: number) => `Similarity below ${n.toFixed(2)} is not compared.`,
      expand: "Show functions",
      collapse: "Hide functions",
      inTests: "test",
    },
    diagrams: {
      title: "Architecture diagrams",
      subtitle: "Module dependencies and call flows, drawn from the code with no model involved.",
      diagram: "Diagram",
      type: "Diagram type",
      modules: "Modules",
      flow: "Call flow",
      scope: "Folder",
      wholeRepo: "Whole repository",
      entry: "Start from",
      pickEntry: "Search for a function to start from",
      orEndpoint: "or an API endpoint",
      pickEndpoint: "Choose an endpoint",
      style: "Style",
      flowchart: "Flowchart",
      sequence: "Sequence",
      depth: "Depth",
      nodes: (n: number) => `${n} ${n === 1 ? "node" : "nodes"}`,
      links: (n: number) => `${n} ${n === 1 ? "link" : "links"}`,
      level: (level: string) => (level === "dir" ? "Grouped by folder" : "One node per file"),
      truncated: "Too large to show in full: showing the best connected parts.",
      cycles: (n: number) => `${n} import ${n === 1 ? "cycle" : "cycles"} highlighted in red`,
      legendSolid: "Call",
      legendDashed: "Low confidence call",
      legendExternal: "Outside the folder",
      copy: "Copy Mermaid",
      copied: "Copied Mermaid source",
      downloadSvg: "SVG",
      downloadMmd: ".mmd",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      fit: "Fit to view",
      open: "Open",
      drawing: "Drawing…",
      renderFailed: "The diagram could not be drawn",
      emptyTitle: "Nothing to draw yet",
      emptyModules: "No imports between files were found.",
      emptyFlowTitle: "Pick where the flow starts",
      emptyFlowBody: "Choose a function, or an API endpoint, to see the calls it makes.",
      noFlow: "This function does not call anything else in the repository.",
      inlineHandler: "This endpoint's handler is an inline function, so there is no flow to draw.",
      showFlow: "Show request flow",
      showFlowFor: (path: string) => `Show the request flow for ${path}`,
    },
    impact: {
      title: "Impact analysis",
      subtitle: "Pick a function, method or class to see what may break if it changes.",
      pick: "Search functions, methods and classes",
      pickHint: "Type a name. Letters in order also match, so “vtok” finds verify_token.",
      clear: "Clear selection",
      depth: "How far to look",
      depthValue: (n: number) => `${n} ${n === 1 ? "level" : "levels"} of callers`,
      blastRadius: "Blast radius",
      blast: { Low: "Low", Medium: "Medium", High: "High" },
      scoreLabel: (score: number) => `score ${score}`,
      direct: "Direct callers",
      affected: "Affected in total",
      files: "Files",
      tests: "Affected tests",
      explain: "Explain risk",
      explaining: "Writing summary…",
      summaryTitle: "In plain words",
      summaryFallback: "Written from the numbers above, because the model gave no usable text.",
      levelTitle: (depth: number) =>
        depth === 1 ? "Direct callers" : `Depth ${depth}: calls something at depth ${depth - 1}`,
      testsTitle: "Affected tests",
      testsHelp: "Tests that reach this code. Run these first.",
      moduleTitle: "Used outside any function",
      moduleHelp: "Top-level code in scripts and modules, which the call graph cannot follow.",
      unresolved: (low: number, unresolved: number) =>
        [
          low > 0 ? `${low} of these links are low confidence` : null,
          unresolved > 0
            ? `${unresolved} calls by the same name could not be matched to any definition`
            : null,
        ]
          .filter(Boolean)
          .join(", and ") + ". Check them by hand.",
      truncated: "Too many callers to list: showing the closest ones.",
      none: (depth: number) =>
        `Nothing calls this within ${depth} ${depth === 1 ? "level" : "levels"}.`,
      noneTitle: "No callers found",
      emptyTitle: "Pick something to analyze",
      emptyBody: "Search for a function, method or class, or start from one of these.",
      suggestions: "Most used",
      callers: (n: number) => `${n} ${n === 1 ? "caller" : "callers"}`,
      confidence: {
        high: "high",
        medium: "medium",
        low: "low",
        highHint: "Defined in the same file or imported by the caller.",
        mediumHint: "The only definition with that name in the repository.",
        lowHint: "Matched by name only; several definitions share it or the receiver is unknown.",
      },
      isTest: "test",
      calledAt: (place: string) => `Called at ${place}`,
    },
    endpoints: {
      title: "API endpoints",
      subtitle: "HTTP routes found in the code, with their full paths.",
      search: "Search paths and handlers",
      allMethods: "All",
      allFrameworks: "All frameworks",
      framework: "Framework",
      method: "Method",
      path: "Path",
      handler: "Handler",
      location: "Location",
      partial: "partial",
      partialHint:
        "The full path could not be worked out: a prefix is computed at run time, or the router is mounted somewhere we cannot follow.",
      emptyTitle: "No API endpoints found",
      emptyBody:
        "Lodestar looks for FastAPI, Flask, Express, Fastify, Koa, NestJS, Spring, Go and ASP.NET routes.",
      noMatches: "No endpoints match these filters",
      noMatchesBody: "Try a different search, or clear a filter.",
      export: "Export",
      sortBy: (column: string) => `Sort by ${column}`,
      shown: (shown: number, total: number) => `${shown} of ${total} shown`,
      openHandler: (path: string) => `Open the handler for ${path}`,
    },
    debt: {
      title: "Tech debt",
      subtitle: "TODO, FIXME and other markers found in code comments.",
      search: "Search comments",
      allTags: "All tags",
      allAges: "Any age",
      older: (days: number) => `Older than ${days} days`,
      folder: "Folder",
      groupBy: "Group by",
      groups: { tag: "Tag", folder: "Folder", topic: "Topic", age: "Age" },
      total: "Total",
      oldest: "Oldest",
      byTag: "By tag",
      exportMd: "Markdown",
      exportCsv: "CSV",
      export: "Export",
      emptyTitle: "No tech debt markers found",
      emptyBody: "No TODO-style comments were found. Nice.",
      noMatches: "Nothing matches these filters",
      noMatchesBody: "Try a different search, or clear a filter.",
      emptyColumn: "None",
      grouping: "Grouping by topic. This can take a minute the first time.",
      groupingFailed: "Topics are unavailable. Showing the list without them.",
      regroup: "Regroup",
      noGit: "Author and age need a Git repository with git installed.",
      by: (who: string) => `by ${who}`,
      ago: (days: number) => (days < 1 ? "today" : `${days}d ago`),
      shown: (shown: number, total: number) => `${shown} of ${total} shown`,
    },
  },

  errors: {
    generic: "Something went wrong.",
    network: "Cannot reach the Lodestar backend. Is it running on port 8000?",
  },

  time: {
    justNow: "just now",
    minutes: (n: number) => `${n} min ago`,
    hours: (n: number) => `${n} h ago`,
    days: (n: number) => `${n} d ago`,
    never: "never",
  },
} as const;
